# Generated by Django 5.2.5 on 2025-09-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_at',
            new_name='due_date',
        ),
    ]
